language: node_js
node_js: v12
addons:
  chrome: stable
before_install:
  - npm install -g @lhci/cli@0.4.x
script:
  - lhci autorun
  - lhci upload --target=lhci --serverBaseUrl=$LHCI_BASE_URL --basicAuth.username=$LHCI_USER --basicAuth.password=$LHCI_PASS
